server:
  port: ${SERVER_PORT:8080}
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}
    certificate: ${SERVER_SSL_CERT:/etc/tls/tls.crt}
    certificate-private-key: ${SERVER_SSL_KEY:/etc/tls/tls.key}
  forward-headers-strategy: framework

spring:
  servlet:
    multipart:
      max-file-size: ${WEB_MEDIA_MAX_MULTIPART_SIZE:6MB}
      max-request-size: ${WEB_MEDIA_MAX_MULTIPART_REQUEST_SIZE:30MB}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  application:
    name: web-portal
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:https://keycloak-platform.apps-crc.testing/realms/master}
            authorization-uri: ${KEYCLOAK_AUTHORIZATION_URI:https://keycloak-platform.apps-crc.testing/realms/master/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:https://keycloak-platform.apps-crc.testing/realms/master/protocol/openid-connect/token}
            user-info-uri: ${KEYCLOAK_USERINFO_URI:https://keycloak-platform.apps-crc.testing/realms/master/protocol/openid-connect/userinfo}
            jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:https://keycloak-platform.apps-crc.testing/realms/master/protocol/openid-connect/certs}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:web-portal}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:changeme}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

app:
  gateway-base-url: ${GATEWAY_BASE_URL:https://api-gateway-ecommerce.apps-crc.testing}
  currency: ${APP_CURRENCY:EUR}
  store-url: ${APP_STORE_URL:https://web-portal-ecommerce.apps-crc.testing}
  keycloak-account-url: ${KEYCLOAK_ACCOUNT_URL:https://keycloak-platform.apps-crc.testing/realms/master/account}
  keycloak-admin-base-url: ${KEYCLOAK_ADMIN_BASE_URL:}
  keycloak-admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
  keycloak-admin-username: ${KEYCLOAK_ADMIN_USER:admin}
  keycloak-admin-password: ${KEYCLOAK_ADMIN_PASS:adminPass}
  keycloak-registration-role: ${KEYCLOAK_REGISTRATION_ROLE:USER}

management:
  endpoints:
    web:
      exposure:
        include: health,info
